name: CI

on:
  push:
    branches: [main, debug]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      
      - name: Setup Node.js
        uses: actions/setup-node@89d709d423dc495668cd762a18dd4a070611be3f
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run check
        run: npm run check
      
      - name: Build
        run: npm run build
