name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions: {}

jobs:
  check-ci:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Wait for CI to pass
        id: wait-for-ci
        uses: fountainhead/action-wait-for-check@5a908a24814494009c4bb27c242ea38c93c593be
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: test
          ref: ${{ github.sha }}
          timeoutSeconds: 1800

      - name: Cancel the release if CI fails
        if: steps.wait-for-ci.outputs.conclusion == 'failure'
        run: exit 1

  release:
    needs: check-ci
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@89d709d423dc495668cd762a18dd4a070611be3f
        with:
          node-version-file: 'package.json'
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm to latest
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build dist
        run: npm run build

      - name: Publish to NPM
        run: npm publish
